import * as THREE from 'three';
import { logger } from 'utils/logger';
import { WORLD_MIN_BOUND, WORLD_MAX_BOUND } from '../constants';
import { RENDER_DISTANCE_CHUNKS, getChunkCoordinates, getChunkKey } from '../chunkUtils';
import type { Grass } from '../ez-tree/environment/grass';
import type { Rocks } from '../ez-tree/environment/rocks';
import type { Trees } from '../ez-tree/environment/trees';
import type { Flowers } from '../ez-tree/environment/flowers';

// Define an interface for the content of a chunk
interface ChunkContent {
  id: string; // Unique identifier for the chunk
  grassMesh: THREE.InstancedMesh | null;
  rocksGroup: THREE.Group | null;
  treesGroup: THREE.Group | null;
  flowersGroup: THREE.Group | null;
  objects: THREE.Object3D[]; // Array to hold all Three.js objects in this chunk for easy removal
  isLoaded: boolean; // Track if chunk content is fully loaded and added to scene
  isDisposed: boolean; // Track if chunk resources are disposed
  gameplayData?: {
    coinSpawns: { position: number[] }[];
    enemySpawns: { position: number[]; coinIndex: number }[];
  };
}

// Interface for chunk data generated by worker
interface ChunkData {
  grassData: {
    positions: number[];
    scales: number[];
    quaternions: number[];
    colors: number[];
  };
  rocksData: {
    positions: number[];
    scales: number[];
    quaternions: number[];
    colors: number[];
  };
  treesData: {
    positions: number[];
    scales: number[];
    quaternions: number[];
    colors: number[];
  };
  flowersData: {
    positions: number[];
    scales: number[];
    quaternions: number[];
    colors: number[];
  };
  gameplayData: {
    coinSpawns: { position: number[] }[];
    enemySpawns: { position: number[]; coinIndex: number }[];
  };
}

export class ChunkManager extends THREE.Object3D {
  private worker: Worker;
  private loadedChunks: Map<string, ChunkContent> = new Map();
  private playerPosition: THREE.Vector3 = new THREE.Vector3();
  private lastPlayerChunk: { chunkX: number; chunkZ: number } | null = null;
  private grassGenerator: Grass;
  private rocksGenerator: Rocks;
  private treesGenerator: Trees;
  private flowersGenerator: Flowers;

  private loadingQueue: string[] = [];
  private unloadingQueue: string[] = [];
  private isProcessingQueue: boolean = false;
  private _generatorsReady: boolean = false; // New flag to indicate if generators are ready
  // Map to store pending promise resolvers for chunk generation
  private pendingResolves = new Map<string, (data: any) => void>();

  constructor(grassGenerator: Grass, rocksGenerator: Rocks, treesGenerator: Trees, flowersGenerator: Flowers) {
    super();
    this.name = 'ChunkManager';

    this.grassGenerator = grassGenerator;
    this.rocksGenerator = rocksGenerator;
    this.treesGenerator = treesGenerator;
    this.flowersGenerator = flowersGenerator;

    this.worker = new Worker(new URL('../../workers/chunkWorker.ts', import.meta.url));
    this.worker.onmessage = (e) => {
      const { chunkKey, grassData, rocksData, treesData, flowersData, gameplayData } = e.data;

      // Check if there is a pending resolver for this chunk
      if (this.pendingResolves.has(chunkKey)) {
        const resolve = this.pendingResolves.get(chunkKey);
        this.pendingResolves.delete(chunkKey);
        if (resolve) resolve(e.data);
      } else {
        // Fallback: Check if chunk exists in loadedChunks and populate it
        // This handles cases where data arrives without a specific pending promise (rare in new flow)
        const chunk = this.loadedChunks.get(chunkKey);
        if (chunk) {
          this.populateChunk(chunk, grassData, rocksData, treesData, flowersData, gameplayData);
          this.addChunkContentToScene(chunk);
          logger.log(`[ChunkManager] Populated chunk ${chunkKey} (Fallback)`);
        }
      }
    };
  }

  public updatePlayerPosition(position: THREE.Vector3): void {
    this.playerPosition.copy(position);
    this.updateChunks();
  }

  private updateChunks(): void {
    const { chunkX: currentPlayerChunkX, chunkZ: currentPlayerChunkZ } = getChunkCoordinates(
      this.playerPosition.x,
      this.playerPosition.z
    );

    if (
      this.lastPlayerChunk &&
      this.lastPlayerChunk.chunkX === currentPlayerChunkX &&
      this.lastPlayerChunk.chunkZ === currentPlayerChunkZ
    ) {
      return;
    }

    this.lastPlayerChunk = { chunkX: currentPlayerChunkX, chunkZ: currentPlayerChunkZ };

    const chunksToKeep: Set<string> = new Set();
    const chunksToLoadNow: string[] = [];
    const chunksToUnloadNow: string[] = [];

    // Determine which chunks should be loaded or kept
    for (let x = -RENDER_DISTANCE_CHUNKS; x <= RENDER_DISTANCE_CHUNKS; x++) {
      for (let z = -RENDER_DISTANCE_CHUNKS; z <= RENDER_DISTANCE_CHUNKS; z++) {
        const targetChunkX = currentPlayerChunkX + x;
        const targetChunkZ = currentPlayerChunkZ + z;
        const chunkKey = getChunkKey(targetChunkX, targetChunkZ);
        chunksToKeep.add(chunkKey);

        if (!this.loadedChunks.has(chunkKey)) {
          chunksToLoadNow.push(chunkKey);
        }
      }
    }

    // Determine which chunks should be unloaded
    for (const [key] of this.loadedChunks.entries()) {
      if (!chunksToKeep.has(key)) {
        chunksToUnloadNow.push(key);
      }
    }

    // Add to queues, prioritizing unloading
    this.unloadingQueue.push(...chunksToUnloadNow);
    this.loadingQueue.push(...chunksToLoadNow);

    if (!this.isProcessingQueue) {
      this.processQueue();
    }
  }

  private async processQueue(): Promise<void> {
    if (this.isProcessingQueue) return;
    this.isProcessingQueue = true;

    // Only proceed with loading if generators are ready
    if (!this._generatorsReady && this.loadingQueue.length > 0) {
      logger.log("[ChunkManager] Generators not yet ready, deferring chunk loading.");
      this.isProcessingQueue = false;
      return;
    }

    // Prioritize unloading
    if (this.unloadingQueue.length > 0) {
      const chunkKey = this.unloadingQueue.shift()!;
      const chunk = this.loadedChunks.get(chunkKey);
      if (chunk) {
        await this.unloadChunk(chunk);
        this.loadedChunks.delete(chunkKey);
      }
    } else if (this.loadingQueue.length > 0) {
      const chunkKey = this.loadingQueue.shift()!;
      const { chunkX, chunkZ } = this.parseChunkKey(chunkKey);
      // Double check if it's still needed and not already loaded
      if (!this.loadedChunks.has(chunkKey)) {
        const newChunk = await this.loadChunkModern(chunkX, chunkZ);
        // Ensure the chunk is still not loaded before setting it
        if (!this.loadedChunks.has(chunkKey)) {
          this.loadedChunks.set(chunkKey, newChunk);
          this.addChunkContentToScene(newChunk);
        }
      }
    }

    this.isProcessingQueue = false;

    // If there's more work, schedule the next processing frame
    if (this.unloadingQueue.length > 0 || this.loadingQueue.length > 0) {
      requestAnimationFrame(() => this.processQueue());
    }
  }

  public setGeneratorsReady(): void {
    this._generatorsReady = true;
    logger.log("[ChunkManager] Generators are ready. Starting queue processing.");
    if (!this.isProcessingQueue) {
      this.processQueue();
    }
  }

  private parseChunkKey(chunkKey: string): { chunkX: number; chunkZ: number } {
    const parts = chunkKey.split(',');
    return { chunkX: parseInt(parts[0]), chunkZ: parseInt(parts[1]) };
  }

  private async loadChunkModern(chunkX: number, chunkZ: number): Promise<ChunkContent> {
    const chunkKey = getChunkKey(chunkX, chunkZ);

    // Check if valid generators - FORCE SUCCESS even if not initialized
    if (!this.grassGenerator || !this.rocksGenerator || !this.treesGenerator || !this.flowersGenerator) {
      logger.warn('[ChunkManager] Generators not fully initialized, creating fallback chunk');
      // Create empty chunk that will be populated later when generators are ready
      const fallbackChunk: ChunkContent = {
        id: chunkKey,
        grassMesh: null,
        rocksGroup: null,
        treesGroup: null,
        flowersGroup: null,
        objects: [],
        isLoaded: true, // Mark as loaded to prevent retries
        isDisposed: false,
        gameplayData: { coinSpawns: [], enemySpawns: [] }
      };
      this.dispatchEvent({ type: 'chunk-loaded', checkChunkKey: chunkKey, chunk: fallbackChunk } as any);
      return fallbackChunk;
    }

    const chunkContent: ChunkContent = {
      id: chunkKey,
      grassMesh: null,
      rocksGroup: null,
      treesGroup: null,
      flowersGroup: null,
      objects: [],
      isLoaded: false,
      isDisposed: false,
      gameplayData: { coinSpawns: [], enemySpawns: [] }
    };

    // FORCE SUCCESS - Retry chunk generation until it works
    const generateChunkWithRetry = async (maxAttempts: number = 10): Promise<ChunkContent> => {
      for (let attempt = 1; attempt <= maxAttempts; attempt++) {
        try {
          return await new Promise<ChunkContent>((resolve, reject) => {
            // Set timeout to prevent hanging
            const timeout = setTimeout(() => {
              reject(new Error('Chunk generation timeout'));
            }, 45000); // 45 second timeout (increased from 10s to handle initial load queue)

            // Register the resolver
            this.pendingResolves.set(chunkKey, (data: any) => {
              clearTimeout(timeout);
              const { grassData, rocksData, treesData, flowersData, gameplayData } = data;

              try {
                this.populateChunk(chunkContent, grassData, rocksData, treesData, flowersData, gameplayData);
                chunkContent.isLoaded = true;
                this.dispatchEvent({ type: 'chunk-loaded', checkChunkKey: chunkKey, chunk: chunkContent } as any);
                resolve(chunkContent);
              } catch (populateError) {
                logger.warn(`[ChunkManager] Failed to populate chunk ${chunkKey}:`, populateError);
                // Still resolve with empty chunk to prevent hanging
                chunkContent.isLoaded = true;
                this.dispatchEvent({ type: 'chunk-loaded', checkChunkKey: chunkKey, chunk: chunkContent } as any);
                resolve(chunkContent);
              }
            });

            this.worker.postMessage({
              chunkX,
              chunkZ,
              grassOptions: this.grassGenerator.options,
              rocksOptions: this.rocksGenerator.options,
              treesOptions: this.treesGenerator.options,
              flowersOptions: this.flowersGenerator.options,
              chunkKey,
              worldMin: WORLD_MIN_BOUND,
              worldMax: WORLD_MAX_BOUND,
            });
          });

        } catch (error) {
          logger.warn(`[ChunkManager] Chunk generation attempt ${attempt} failed for ${chunkKey}:`, error);

          if (attempt < maxAttempts) {
            // Wait before retry
            await new Promise(resolve => setTimeout(resolve, 1000 * attempt));
          } else {
            // Final attempt - force success with empty chunk
            logger.error(`[ChunkManager] All attempts failed for chunk ${chunkKey}, creating empty chunk`);
            chunkContent.isLoaded = true;
            this.dispatchEvent({ type: 'chunk-loaded', checkChunkKey: chunkKey, chunk: chunkContent } as any);
            return chunkContent;
          }
        }
      }

      // This should never be reached due to the return in the final attempt
      return chunkContent;
    };

    return generateChunkWithRetry();
  }

  private populateChunk(chunk: ChunkContent, grassData: {
    positions: number[];
    scales: number[];
    quaternions: number[];
    colors: number[];
  }, rocksData: {
    positions: number[];
    scales: number[];
    quaternions: number[];
    colors: number[];
  }, treesData: {
    positions: number[];
    scales: number[];
    quaternions: number[];
    colors: number[];
  }, flowersData: {
    positions: number[];
    scales: number[];
    quaternions: number[];
    colors: number[];
  }, gameplayData: {
    coinSpawns: { position: number[] }[];
    enemySpawns: { position: number[]; coinIndex: number }[];
  }): void {
    if (!this.grassGenerator || !this.rocksGenerator || !this.treesGenerator || !this.flowersGenerator) {
      logger.error('Generators not initialized');
      return;
    }

    // Helper function to get terrain height at a specific point
    const getHeightAt = (x: number, z: number): number => {
      // Search for ground in the scene to determine height
      // This is assumed and may need modification based on how terrain data is stored in your project
      try {
        // Try to find ground object in the scene
        let ground: THREE.Object3D | null = null;
        this.traverse((child) => {
          if (child.name === 'Ground') {
            ground = child;
          }
        });

        if (ground && (ground as any).type === 'Mesh' && 'geometry' in ground) {
          // Use Raycaster to determine height of point on ground surface
          const raycaster = new THREE.Raycaster();
          const direction = new THREE.Vector3(0, -1, 0);
          const origin = new THREE.Vector3(x, 1000, z); // High point above terrain
          raycaster.set(origin, direction);

          const intersects = raycaster.intersectObject(ground);
          if (intersects.length > 0) {
            return intersects[0].point.y;
          }
        }
      } catch (error) {
        logger.warn('Error determining terrain height:', error);
      }

      // Default value if unable to determine height
      return 0;
    };

    // Generate and add grass
    if (grassData.positions.length > 0) {
      const grassMesh = this.grassGenerator.generateGrassFromData(grassData);
      if (grassMesh) {
        chunk.grassMesh = grassMesh;
        chunk.objects.push(grassMesh);
      }
    }

    // Generate and add rocks
    if (rocksData.positions.length > 0) {
      const rocksGroup = this.rocksGenerator.generateRocksFromData(rocksData);
      if (rocksGroup) {
        chunk.rocksGroup = rocksGroup;
        chunk.objects.push(rocksGroup);
      }
    }

    // Generate and add trees
    if (treesData.positions.length > 0) {
      const treesGroup = this.treesGenerator.generateTreesFromData(treesData);
      if (treesGroup) {
        chunk.treesGroup = treesGroup;
        chunk.objects.push(treesGroup);
      }
    }

    // Generate and add flowers - flowers are at ground level like grass
    if (flowersData.positions.length > 0) {
      const flowersGroup = this.flowersGenerator.generateFlowersFromData(flowersData);
      if (flowersGroup) {
        chunk.flowersGroup = flowersGroup;
        chunk.objects.push(flowersGroup);
      }
    }

    chunk.isLoaded = true;
    if (gameplayData) {
      chunk.gameplayData = gameplayData;
    }
  }

  public getGameplaySpawns(chunkKey: string): { coinSpawns: { position: number[] }[]; enemySpawns: { position: number[]; coinIndex: number }[] } | null {
    const chunk = this.loadedChunks.get(chunkKey);
    if (chunk && chunk.gameplayData) {
      return chunk.gameplayData;
    }
    return null;
  }

  private addChunkContentToScene(chunk: ChunkContent): void {
    logger.log(`[ChunkManager] Adding chunk ${chunk.id} content to scene with ${chunk.objects.length} objects`);

    chunk.objects.forEach(obj => {
      this.add(obj);

      // Apply shadow settings specifically to the new object
      if (obj instanceof THREE.InstancedMesh) {
        obj.castShadow = true;
        obj.receiveShadow = true;
        obj.frustumCulled = true;
      } else {
        // Recursively enable shadows for all Meshes in Groups (like Trees)
        obj.traverse((child) => {
          if (child instanceof THREE.Mesh) {
            child.castShadow = true;
            child.receiveShadow = true;
            child.frustumCulled = true;

            if (child.material) {
              const materials = Array.isArray(child.material) ? child.material : [child.material];
              materials.forEach(mat => mat.needsUpdate = true);
            }
          }
        });
      }

      logger.log(`[ChunkManager] Added object ${obj.name || 'unnamed'} to scene`);
    });
  }

  private async unloadChunk(chunk: ChunkContent): Promise<void> {
    if (chunk.isDisposed) return; // Already disposed

    chunk.objects.forEach(obj => {
      this.remove(obj);
      // Dispose of geometries and materials if necessary to free up memory
      if (obj instanceof THREE.InstancedMesh) {
        obj.geometry.dispose();
        if (Array.isArray(obj.material)) {
          obj.material.forEach(mat => mat.dispose());
        } else {
          obj.material.dispose();
        }
      } else if (obj instanceof THREE.Group) {
        if (chunk.treesGroup === obj) {
          this.treesGenerator.disposeChunk(obj);
        } else if (chunk.rocksGroup === obj) {
          this.rocksGenerator.disposeChunk(obj); // Assuming Rocks also has a disposeChunk method
        } else if (chunk.flowersGroup === obj) {
          this.flowersGenerator.disposeChunk(obj);
        }
        obj.clear();
      }
    });
    chunk.objects = [];
    chunk.isLoaded = false;
    chunk.isDisposed = true; // Mark as disposed
  }

  public updateModern(elapsedTime: number): void {
    this.traverse((o) => {
      if ((o as THREE.Mesh).isMesh && (o as THREE.Mesh).material) {
        const materials = (Array.isArray((o as THREE.Mesh).material) ? (o as THREE.Mesh).material : [(o as THREE.Mesh).material]) as THREE.Material[];
        materials.forEach((mat: THREE.Material) => {
          if ((mat as THREE.MeshPhongMaterial).userData?.shader) {
            const shader = (mat as THREE.MeshPhongMaterial).userData.shader as { uniforms: { uTime: { value: number } } };
            shader.uniforms.uTime.value = elapsedTime;
          }
        });
      }
    });

    // Update trees separately, assuming they have a different update mechanism.
    if (this.treesGenerator) {
      this.treesGenerator.update(elapsedTime);
    }
    // Flowers update method removed for consistency with Rocks class
    // No update needed for flowers as they don't have animation or wind effects
  }

  /**
   * Generate a single chunk asynchronously for preloading purposes
   * Used for initial scene setup without affecting the main loading queue
   */
  public async generateChunkAsync(chunkX: number, chunkZ: number): Promise<void> {
    const chunkKey = getChunkKey(chunkX, chunkZ);

    // Skip if already loaded
    if (this.loadedChunks.has(chunkKey)) {
      return;
    }

    try {
      const chunkContent = await this.loadChunkModern(chunkX, chunkZ);

      // Ensure the chunk is still not loaded before setting it
      if (!this.loadedChunks.has(chunkKey)) {
        this.loadedChunks.set(chunkKey, chunkContent);
        this.addChunkContentToScene(chunkContent);
        logger.log(`[ChunkManager] Preloaded chunk ${chunkKey}`);
      }
    } catch (error) {
      logger.error(`[ChunkManager] Failed to preload chunk ${chunkKey}:`, error);
      // Don't throw - allow game to continue
    }
  }

  public dispose(): void {
    this.loadedChunks.forEach((chunkContent, chunkKey) => {
      this.unloadChunk(chunkContent);
      logger.log(`[ChunkManager] Disposed chunk ${chunkKey}`);
    });

    this.loadedChunks.clear();
    this.loadingQueue = [];
    this.unloadingQueue = [];

    this.worker.terminate();

    logger.log('[ChunkManager] Disposed chunk manager');
  }
}
